from django.contrib import admin
from models import *

admin.site.register(Customer)
admin.site.register(Employee)
admin.site.register(ProductType)
admin.site.register(Product)
admin.site.register(Exercise)
admin.site.register(CustomerDetailAttribute)
admin.site.register(CustomerDetail)
admin.site.register(AttributeDetail)
admin.site.register(ExerciseDetail)
admin.site.register(ClassType)
admin.site.register(Location)
admin.site.register(Government)
admin.site.register(ProductCategory)
admin.site.register(ProductBrand)
admin.site.register(Shipment)
#admin.site.register(Trainers_skill)
admin.site.register(Trainer)
#admin.site.register(Classes_attendees)
admin.site.register(Class)
admin.site.register(SpaUsage)
admin.site.register(MachinesUsage)
admin.site.register(Service)
admin.site.register(Package)
admin.site.register(PackageDetail)
admin.site.register(Order)
admin.site.register(OrderDetail)
admin.site.register(Membership)